cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'the_silver_searcher'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'vim'
brew 'tmux'
brew 'imagemagick'
brew 'git'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'unrar'

cask '1password'
cask 'google-chrome'
cask 'handbrake'
cask 'slack'
cask 'transmission'
cask 'tunnelbear'
cask 'vlc'
